//RANCANGLAH ANALISIS KONSEPTUAL  OOP UNUTK KASUS BENGKEL TERSEBUT DENGAN MENJAWAB POIN POIN BERIKUT
//1. Tentukan class apa saja yang dibutuhkan dalam sistem tersebut, lalu jelaskan alasan pemilihannya.
//Jawaban : KENDARAAN, MOBIL, MOTOR, dan MAIN. Kendaraan sebagai class induk karena memiliki atribut dan method umum yang dimiliki oleh semua jenis kendaraan, seperti nomor polisi, tahun kendaraan, dan status servis. Mobil dan Motor sebagai class turunan karena memiliki atribut dan method khusus yang membedakan keduanya, seperti jumlah pintu dan tipe transmisi untuk mobil, serta jenis mesin dan kapasitas tangki untuk motor. Main sebagai class untuk menjalankan program dan menguji program dari class Kendaraan, Mobil, dan Motor.
//2. Identifikasi atribut dan method yang sebaiknya ditempatkan pada class induk dan class turunan.
//Jawaban : Pada class Kendaraan, atribut yang sebaiknya ditempatkan adalah nomorPolisi, tahunKendaraan, dan statusServis karena atribut tersebut umum dimiliki oleh semua jenis kendaraan. Method yang sebaiknya ditempatkan adalah tampilkanInfo() untuk menampilkan informasi kendaraan dan ubahStatusServis() untuk mengubah status servis kendaraan. Pada class Mobil, atribut yang sebaiknya ditempatkan adalah jumlahPintu dan tipeTransmisi karena atribut tersebut khusus dimiliki oleh mobil. Method yang sebaiknya ditempatkan adalah tampilkanInfo() untuk menampilkan informasi mobil dan ubahStatusServis() untuk mengubah status servis mobil. Pada class Motor, atribut yang sebaiknya ditempatkan adalah jenisMesin dan kapasitasTangki karena atribut tersebut khusus dimiliki oleh motor. Method yang sebaiknya ditempatkan adalah tampilkanInfo() untuk menampilkan informasi motor dan ubahStatusServis() untuk mengubah status servis motor.
//3. Jelaskan bagaimmana constructor digunakan agar objek kendaraan selalu mamiliki data awal yang valid saat dibuat.
//Jawaban : Constructor digunakan untuk menginisialisasi objek kendaraan dengan data awal yang valid saat dibuat. Pada class Kendaraan, constructor menerima parameter nomorPolisi, tahunKendaraan, dan statusServis untuk memastikan bahwa setiap objek kendaraan yang dibuat memiliki informasi dasar yang lengkap. Pada class Mobil dan Motor, constructor juga menerima parameter tambahan yang spesifik untuk jenis kendaraan tersebut, seperti jumlahPintu dan tipeTransmisi untuk mobil, serta jenisMesin dan kapasitasTangki untuk motor. Dengan menggunakan constructor, kita dapat memastikan bahwa setiap objek kendaraan yang dibuat memiliki data awal yang valid dan lengkap sesuai dengan jenis kendaraannya.
//4. Analisis bagaimana enkapsulasi diterapkan untuk melindungi data kendaraan khususnya pada atribut statusServis
//Jawaban : Enkapsulasi diterapkan dengan menjadikan atribut statusServis sebagai private, sehingga tidak dapat diakses langsung dari luar class. Untuk mengakses dan memodifikasi statusServis, disediakan method getter dan setter yaitu getStatusServis() dan setStatusServis(). Dengan cara ini, kita dapat mengontrol bagaimana statusServis diubah dan memastikan bahwa data tersebut tetap valid. 
//Jawaban : Inheritance tepat digunakan pada kasus ini karena Mobil dan Motor memiliki banyak atribut dan method yang sama dengan Kendaraan, seperti nomorPolisi, tahunKendaraan, dan statusServis. Dengan menggunakan inheritance, kita dapat menghindari duplikasi kode dan memudahkan pemeliharaan program. Kendaraan lebih cocok menjadi superclass karena merupakan konsep umum yang mencakup semua jenis kendaraan, sedangkan Mobil dan Motor adalah turunan dari kendaraan tersebut. Dengan menjadikan Kendaraan sebagai superclass, kita dapat dengan mudah menambahkan jenis kendaraan lain di masa depan tanpa harus mengubah struktur dasar dari program, cukup dengan membuat class baru yang mewarisi dari Kendaraan.
//6. Berikan contoh minimal satu objek nyata dari class Mobil atau Motor, lalu jelaskan nilai atribut yang dimiliki objek tersebut.
//Jawaban : Contoh objek nyata dari class Mobil adalah mobil dengan nomor polisi "N 5678 EF", tahun kendaraan "2019", status servis "Servis Ringan", jumlah pintu 4, dan tipe transmisi "Otomatis". Nilai atribut tersebut menunjukkan bahwa mobil tersebut memiliki nomor polisi yang unik, diproduksi pada tahun 2019, saat ini dalam kondisi servis ringan, memiliki 4 pintu, dan menggunakan transmisi otomatis.

